#!/usr/bin/env python3
"""Post-provision helper: reads Terraform outputs and writes .env.azure files.

Usage:
    python scripts/write_env_from_tf.py [--infra-dir infra]

Reads `terraform output -json` from the infra directory and writes
py/apps/vin-insight/.env.azure and ts/apps/ui/.env.azure with all provisioned values.

This is an alternative to the shell-based postprovision.sh for environments
where azd is not available (e.g. manual Terraform runs).
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


def get_tf_outputs(infra_dir: Path) -> dict[str, str]:
    """Run `terraform output -json` and return a flat {key: value} dict."""
    result = subprocess.run(
        ["terraform", "output", "-json"],
        cwd=infra_dir,
        capture_output=True,
        text=True,
        check=True,
    )
    raw = json.loads(result.stdout)
    return {k: v["value"] for k, v in raw.items()}


def o(outputs: dict[str, str], key: str) -> str:
    """Get an output value, case-insensitive, default empty string."""
    return outputs.get(key, outputs.get(key.upper(), ""))


def write_backend_env(outputs: dict[str, str], dest: Path) -> None:
    """Write py/apps/vin-insight/.env.azure with Terraform-provisioned values."""
    lines = [
        "# Auto-generated by write_env_from_tf.py — do not edit manually",
        "",
        "# ── Runtime ──",
        "OTEL_EXPORTER=azure",
        "FOUNDRY_CREDENTIAL_MODE=managed_identity",
        "",
        "# ── Foundry ──",
        f"FOUNDRY_PROJECT_ENDPOINT={o(outputs, 'AZURE_AI_FOUNDRY_PROJECT_ENDPOINT')}",
        f"FOUNDRY_MODEL_DEPLOYMENT_NAME={o(outputs, 'AZURE_OPENAI_DEPLOYMENT_FULL')}",
        "",
        "# ── NHTSA ──",
        "NHTSA_API_BASE_URL=https://vpic.nhtsa.dot.gov/api/vehicles",
        "",
        "# ── Observability ──",
        f"APPLICATIONINSIGHTS_CONNECTION_STRING={o(outputs, 'AZURE_APPINSIGHTS_CONNECTION_STRING')}",
        "",
        "# ── Server ──",
        "API_HOST=0.0.0.0",
        "API_PORT=8001",
        "LOG_LEVEL=INFO",
        f"CORS_ORIGINS={o(outputs, 'SERVICE_FRONTEND_URI')}",
    ]
    dest.write_text("\n".join(lines) + "\n")
    print(f"  Wrote {dest}")


def write_frontend_env(outputs: dict[str, str], dest: Path) -> None:
    """Write ts/apps/ui/.env.azure with all Terraform-provisioned values."""
    lines = [
        "# Auto-generated by write_env_from_tf.py — do not edit manually",
        "",
        f"VITE_BACKEND_URL={o(outputs, 'SERVICE_VIN_INSIGHT_URI')}",
        "VITE_APP_INSIGHTS_TRACE_URL=",
    ]
    dest.write_text("\n".join(lines) + "\n")
    print(f"  Wrote {dest}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate .env.azure files from Terraform outputs"
    )
    parser.add_argument(
        "--infra-dir",
        default="infra",
        help="Terraform directory (default: infra)",
    )
    args = parser.parse_args()

    infra_dir = Path(args.infra_dir)
    if not (infra_dir / "main.tf").exists():
        print(f"Error: {infra_dir}/main.tf not found", file=sys.stderr)
        sys.exit(1)

    print("── Reading Terraform outputs ──")
    outputs = get_tf_outputs(infra_dir)

    print("── Writing .env.azure files ──")
    write_backend_env(outputs, Path("py/apps/vin-insight/.env.azure"))
    write_frontend_env(outputs, Path("ts/apps/ui/.env.azure"))
    print("── Done ──")


if __name__ == "__main__":
    main()
