#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
#  Post-provision hook — runs after `azd provision`
#
#  1. Reads Terraform outputs from the azd environment
#  2. Sets CORS and VITE_BACKEND_URL for the next deploy
#  3. Generates .env.azure reference files for local dev
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

echo "── Post-provision: reading Terraform outputs ──"

# Helper: read azd env value (returns empty string if missing)
get() { azd env get-value "$1" 2>/dev/null || echo ""; }

BACKEND_URI=$(get SERVICE_BACKEND_URI)
FRONTEND_URI=$(get SERVICE_FRONTEND_URI)
COSMOS_ENDPOINT=$(get AZURE_COSMOS_ENDPOINT)
COSMOS_DB_NAME=$(get AZURE_COSMOS_DATABASE_NAME)
OPENAI_ENDPOINT=$(get AZURE_OPENAI_ENDPOINT)
OPENAI_DEPLOY_FULL=$(get AZURE_OPENAI_DEPLOYMENT_FULL)
OPENAI_API_VERSION=$(get AZURE_OPENAI_API_VERSION)
MI_CLIENT_ID=$(get AZURE_MANAGED_IDENTITY_CLIENT_ID)
APPINSIGHTS_CS=$(get AZURE_APPINSIGHTS_CONNECTION_STRING)
FOUNDRY_ENDPOINT=$(get AZURE_AI_FOUNDRY_PROJECT_ENDPOINT)

echo "  Backend URI:   ${BACKEND_URI}"
echo "  Frontend URI:  ${FRONTEND_URI}"

# ── Set CORS + VITE_BACKEND_URL for next deploy ──

if [ -n "${FRONTEND_URI}" ]; then
  echo "── Setting backend CORS to allow frontend origin ──"
  azd env set CORS_ORIGINS "${FRONTEND_URI}"
fi

if [ -n "${BACKEND_URI}" ]; then
  echo "── Setting VITE_BACKEND_URL for frontend ──"
  azd env set VITE_BACKEND_URL "${BACKEND_URI}"
fi

# ── Generate .env.azure files for local reference ──

echo "── Generating .env.azure files ──"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"

cat > "${ROOT_DIR}/py/apps/vin-insight/.env.azure" <<EOF
# ═══════════════════════════════════════════════════════════════
# Auto-generated by postprovision.sh — do not edit manually
# Run 'azd provision' to regenerate after infra changes.
# ═══════════════════════════════════════════════════════════════

# ── Observability ──
OTEL_EXPORTER=azure

# ── Azure AI Foundry ──
FOUNDRY_PROJECT_ENDPOINT=${FOUNDRY_ENDPOINT}
FOUNDRY_MODEL_DEPLOYMENT_NAME=gpt-4-1
FOUNDRY_CREDENTIAL_MODE=managed_identity

# ── Cosmos DB ──
STORAGE_MODE=cosmos
COSMOS_ENDPOINT=${COSMOS_ENDPOINT}
COSMOS_DATABASE_NAME=${COSMOS_DB_NAME}

# ── Identity ──
AZURE_CLIENT_ID=${MI_CLIENT_ID}

# ── Observability ──
APPLICATIONINSIGHTS_CONNECTION_STRING=${APPINSIGHTS_CS}

# ── Server ──
API_HOST=0.0.0.0
API_PORT=8001
LOG_LEVEL=INFO
CORS_ORIGINS=${FRONTEND_URI}
EOF
echo "  Wrote py/apps/vin-insight/.env.azure"

cat > "${ROOT_DIR}/ts/apps/ui/.env.azure" <<EOF
# ═══════════════════════════════════════════════════════════════
# Auto-generated by postprovision.sh — do not edit manually
# Run 'azd provision' to regenerate after infra changes.
# ═══════════════════════════════════════════════════════════════

VITE_BACKEND_URL=${BACKEND_URI}
EOF
echo "  Wrote ts/apps/ui/.env.azure"

echo "── Post-provision complete ──"
